### ISSUE TITLE
Tag dropdown not darkened, text is invisible

### ISSUE THREAD

**Issue by iarp** [domainzero/bookstack-dark-theme#10]
![Untitled](https://user-images.githubusercontent.com/2169438/56841079-8983b900-6859-11e9-8c06-800c6e138741.png)

**Comment by domainzero** [comment]
Hey @iarp
Looks like slapping this in the extra CSS file didn't fix the issue, but putting it in the **Custom HTML head content** did. 
```css
.suggestion-box {
    background-color: #282a36!important;
    border: 1px solid #BBB;
    box-shadow: none!important;
    border-radius: 0!important; 
}
.suggestion-box li:last-child {
    border-bottom: 0; 
}
.suggestion-box li.active {
    background-color: #44475a!important; 
}
```

![image](https://user-images.githubusercontent.com/7740725/57572480-97e8dd80-73e0-11e9-8186-26ce3a5e9f15.png)
